### ISSUE TITLE
problem in the range to generate random timestamp

### ISSUE THREAD

**Issue by yzchang** [eXascaleInfolab/TSM-Bench#42]
The code generates random timestamps in the range ["2019-04-01T00:00:00", "2019-04-30T00:00:00"], while the time range in "d1.csv" is [2019-03-01 00:00:00, 2019-04-29 23:59:50], and in "d2.csv" is [2019-02-01 00:00:00, 2019-02-10 23:59:50].

A flexible and secure way would be to query the to-be-tested DBMS for the actual min and max of the "time" column

```
$ grep -r random_date *
clickhouse/run_system.py:               date = random_date("2019-04-30T00:00:00", "2019-04-01T00:00:00" , set_date[(int(rangeL)*it)%500], dform = '%Y-%m-%dT%H:%M:%S')
druid/run_system.py:            date = random_date(args.min_ts, args.max_ts, set_date[(int(rangeL)*it)%500], dform = '%Y-%m-%d %H:%M:%S')
extremedb/run_system.py:                date = random_date("2019-04-01T00:00:00", "2019-04-30T00:00:00", set_date[(int(rangeL)*it)%500], dform = '%Y-%m-%dT%H:%M:%S')
influx/run_system.py:from utils.library import random_date
influx/run_system.py:           date = random_date("2019-04-30T00:00:00", "2019-04-01T00:00:00", set_date[(int(rangeL)*it)%500], dform = '%Y-%m-%dT%H:%M:%S')
integration/run_system_template.py:        date = random_date("2019-04-01T00:00:00", "2019-04-30T00:00:00", set_date[(int(rangeL)*it)%500], dform = '%Y-%m-%dT%H:%M:%S')
monetdb/run_system.py:          date = random_date("2019-04-01T00:00:00", "2019-04-30T00:00:00", set_date[(int(rangeL)*it)%500], dform = '%Y-%m-%dT%H:%M:%S')
grep: monetdb/.run_system.py.swp: binary file matches
questdb/run_system.py:          date = random_date("2019-04-01T00:00:00", "2019-04-30T00:00:00", set_date[(int(rangeL)*it)%500], dform = '%Y-%m-%dT%H:%M:%S')
timescaledb/run_system.py:              date = random_date("2019-04-30T00:00:00", "2019-04-01T00:00:00" , set_date[(int(rangeL)*it)%500], dform = '%Y-%m-%dT%H:%M:%S')
```

**Comment by AKheli** [comment]
Thank you for pointing out the issue with station ID selection. We found that the choice of stations had minimal impact on the overall system performance. We have addressed this nonetheless by enabling specifying the number of stations for a given dataset, ensuring that the queries are appropriately scoped. This manual input method provides better control over the data subset used for performance analysis.

**Comment by AKheli** [comment]
Thank you for pointing out the issue with station ID selection. We found that the choice of stations had minimal impact on the overall system performance. We have addressed this nonetheless by enabling specifying the number of stations for a given dataset, ensuring that the queries are appropriately scoped. This manual input method provides better control over the data subset used for performance analysis.

**Comment by AKheli** [comment]
The default timestamp configuration in the code is tailored to align with the time range observed in "d1". However, for scenarios where the datasets vary, such as with "d2.csv", the system supports specifying custom --min_ts and --max_ts parameters as explained in the README file.

**Comment by AKheli** [comment]
The default timestamp configuration in the code is tailored to align with the time range observed in "d1". For other datasets with different timeline, such as with "d2", the system supports specifying custom --min_ts and --max_ts parameters as explained in the README file.
